.TH CONNECT 1 "May 2026" "connect-bot" "User Commands"

.SH NAME
connect \- ANSI C Connect 4 engine with Game Review

.SH SYNOPSIS
.B connect
.RI [ options ]

.SH DESCRIPTION
.B connect
is a lightweight Connect 4 engine written in portable ANSI C.

.SH OPTIONS
.TP
.BR --help ", " -?
Show the help message.

.TP
.BR --depth ", " -d " <depth>"
Specify the engine search depth.

.TP
.BR --player1 ", " -1 " <human|bot>"
Specify whether Player 1 is controlled by a human or the engine.

.TP
.BR --player2 ", " -2 " <human|bot>"
Specify whether Player 2 is controlled by a human or the engine.

.TP
.BR --start ", " -s " <red|yellow>"
Specify which colour starts first.

.TP
.BR --highlight ", " -h
Highlight the latest move.

.TP
.BR --review ", " -r " <game>"
Review a game from its game code.

.SH AUTHOR
GamerZero9512
