.TH CONNECT 1 "May 2026" "connect-bot 1.0" "User Commands"

.SH NAME
connect \- ANSI C Connect 4 engine

.SH SYNOPSIS
.B connect
.RI [ options ]

.SH DESCRIPTION
.B connect
is a lightweight Connect 4 engine written in portable ANSI C.

.SH OPTIONS
.TP
.BR --help ", " -?
Show the help message.

.TP
.BR --depth ", " -d " <depth>"
Specify the engine search depth.

.TP
.BR --red ", " -1 " <human|bot>"
Specify whether Red is controlled by a human or the engine.

.TP
.BR --yellow ", " -2 " <human|bot>"
Specify whether Yellow is controlled by a human or the engine.

.TP
.BR --start ", " -s " <red|yellow>"
Specify which colour starts first.

.TP
.BR --highlight ", " -h
Highlight the latest move.

.SH AUTHOR
GamerZero9512
